version: '3'
services:
  webserver:
    image: nginx:alpine
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - api
  
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - api

  server1:
    image: node:alpine
    working_dir: /home/app
    volumes:
      - .:/home/app
    command: node app.js
    environment: 
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - api

  server2:
    image: node:alpine
    working_dir: /home/app
    volumes:
      - .:/home/app
    command: node app.js
    environment: 
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - api
  
  client1:
    image: node:alpine
    working_dir: /home/app
    volumes:
      - ../client:/home/app
    command: node index.js
    environment:
      API_HOST: http://webserver
      CLIENT_ID: client1
    networks:
      - api

  client2:
    image: node:alpine
    working_dir: /home/app
    volumes:
      - ../client:/home/app
    command: node index.js
    environment:
      API_HOST: http://webserver
      CLIENT_ID: client2
    networks:
      - api
  
  client3:
    image: node:alpine
    working_dir: /home/app
    volumes:
      - ../client:/home/app
    command: node index.js
    environment:
      API_HOST: http://webserver
      CLIENT_ID: client3
    networks:
      - api

networks:
  api: